### ISSUE TITLE
1.0 Launch checklist

### ISSUE THREAD

**Issue by mathetos** [mathetos/my-plugin-info-widget#1]
- [x] Get reviews setting to work properly (See #2)
- [x] Cache call to the api properly (See #3)
- [x] Clear the API cache every time the widget is saved (See #4)
- [x] ~~Cache the widget settings properly (See #5)~~
- [x] ~~Clear the widget settings every time a post is saved (See #6)~~
- [x] Target tab switching per widget, not ALL widgets (See #8)
- [ ] Give setting to display plugin name as Slug or Name (See #9)
